on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up SSH key and known hosts
      run: |
       mkdir -p ~/.ssh
       install -m 600 -D /dev/null ~/.ssh/id_rsa
       echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
       ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
       chmod 700 ~/.ssh
       chmod 600 ~/.ssh/id_rsa
       echo "Known hosts:"
       cat ~/.ssh/known_hosts


    - name: Deploy to Remote Server
      run: |
         ssh -i ~/.ssh/id_rsa python@157.180.21.103 << 'EOF'
           cd /home/python || exit 1

          echo "Pulling latest code..."
          git pull origin main

          echo "Activating virtual environment..."
          source venv/bin/activate

          echo "Installing dependencies..."
          pip install -r requirements.txt

          echo "Running Django migrations..."
          python manage.py migrate

          echo "Collecting static files..."
          python manage.py collectstatic --noinput

          echo "Restarting Django app via PM2..."
          pm2 delete project_name_process || true
          pm2 start project_name_process.sh --name project_name_process

          pm2 save
          EOF
